name: Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create dr-ext Archive Release
        uses: thedoctor0/zip-release@master
        with:
          path: ./dr-ext
          filename: 'dr-ext.zip'
      - name: Create rr-ext Archive Release
        uses: thedoctor0/zip-release@master
        with:
            path: ./rr-ext
            filename: 'rr-ext.zip'
      - name: Upload dr-ext Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dr-ext.zip, rr-ext.zip'
          token: ${{ secrets.GITHUB_TOKEN }}